Python encryptor solution
Khaymon/python_encryptor pull request #1
Opened 2020-11-27 20:08 UTC by Khaymon

2020-12-07 23:37 UTC, ivanaxe requested changes

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +        if letter not in string.ascii_lowercase and letter not in string.ascii_uppercase:
Лучше обойтись одной проверкой not in

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +            error("Unable to open a file: " + e.filename, FILE_OPEN_ERROR_CODE)
Здесь выглядит странно ловить FileNotFound и не ловить все другие возможные проблемы при открытии файла (например не хватает прав, файл является специальным файлом, не поддерживающим open(), io-ошибка и возможно какие-то ещё варианты).

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +    while not end_of_file:
Этот паттерн скопирован трижды. Его стоит унести в отдельный итератор.

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +def prepare_files(input_file_name, output_file_name):
Не очень очевидно, зачем выделять в отдельный блок именно prepare_files.
Логичнее было бы открыть файлы "уровнем выше" и передавать в функции шифровки/дешифровки уже открытые потоки -- это и уменьшит бойлерплейт внутри самих функций и облегчит тестирование.

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +            else:
Не вижу причин не пользоваться elif и дальше

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +def train_model():
Так делать не стоит.
Гораздо лучше все значимые параметры передать явно или внутри класса эсли сделать эту функцию методом класса.

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +def encode_text():
Чтобы не писать сложный двухступенчатый роутер логики, можно сделать базовый сласс Cipher и отнаследовать ViegenereCipher и CaesarCipher с явно имплементированными специфичными методами.
Тогда будет достаточно инстанцировать экземпляр шифра нужного типа и вызвать у него нужный метод.
При этом кода можно написать _ещё_меньше_кода_(это со звёздочкой), если наследовать ViegenereCipher и CaesarCipher от абстрактного класса шифров ShiftCipher, в котором будут реализованы encrypt и decrypt, но останется нереализованным генератор сдвига.

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +    for current_shift in range(1, alphabet_size):
А почему бы не воспользоваться тут уже реализованными encrypt/decrypt?

2020-12-07 23:37 UTC, ivanaxe commented on encryptor.py
> +    data = defaultdict(int)
А почему не Counter?

2020-12-12 22:15 UTC, Khaymon commented on encryptor.py
> +    for current_shift in range(1, alphabet_size):
Для encrypt и decrypt понадобятся лишние записи в файл, а так мы просто делаем сдвиг в current_data и смотрим, как изменилась метрика.

2020-12-12 23:02 UTC, Khaymon commented on encryptor.py
> +        if letter not in string.ascii_lowercase and letter not in string.ascii_uppercase:
Исправил

2020-12-12 23:03 UTC, Khaymon commented on encryptor.py
> +            error("Unable to open a file: " + e.filename, FILE_OPEN_ERROR_CODE)
Поправил. Теперь ловит все

2020-12-12 23:03 UTC, Khaymon commented on encryptor.py
> +    while not end_of_file:
Сделал file_iterator

2020-12-12 23:04 UTC, Khaymon commented on encryptor.py
> +def prepare_files(input_file_name, output_file_name):
Добавил открытие файлов в конструкторе класса Cipher

2020-12-12 23:04 UTC, Khaymon commented on encryptor.py
> +            else:
Исправил

2020-12-12 23:04 UTC, Khaymon commented on encryptor.py
> +def train_model():
Исправил. Добавил классы.

2020-12-12 23:05 UTC, Khaymon commented on encryptor.py
> +def encode_text():
Добавлены Cipher, CaesarCipher, ViegenereCipher.

2020-12-12 23:05 UTC, Khaymon commented on encryptor.py
> +    data = defaultdict(int)
Исправил на Counter

2020-12-24 01:44 UTC, ivanaxe requested changes
Стало сильно лучше, но ещё есть точки для роста.

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +    def __del__(self):
Тут есть проблема : при удалении объекта мы можем нечаяно закрыть stdin или stdout.
В более сложной программе такой код может привести к недетерминированным (из-за отложенного удаления) проблемам.

Я бы вообще всю логику работы с файлами оставил за рамками класса.
Так получится класс, назначение которого -- шифровка/расшифровка любых данных, которые попадут к нему на вход и немножко обвязки, смысл которой заключается в том, чтобы позаботиться о корректной работе с файлами. Такой класс легче переиспользовать и легче тестировать.

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +        if not key.isdecimal():
1. Проще попробовать привести к int'у. Если получилось, то ключ валиден.
2. Чтобы не писать этого дважды, можно выделить в отдельный метод.
3. Раз уж в обоих классах будет валидатор ключа, то можно вызывать его прямо в конструкторе базового класса.

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +        for letter in buffer:
`for letter in input_file` -- всё, что здесь нужно.

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +def parse(argument):
Давай оставим это так, но вообще почти никогда не надо писать парсер командной строки, он уже написан и входит в стандартную библиотеку (а более удобные парсеры тоже написаны, но в виде отдельных библиотечек)

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +            data[letter.lower()] += 1
Здесь ты пользуешься Counter'ом как обычным defaultdict'ом?
Можно же совсем коротко написать `return Counter((letter for letter in text if letter in alphabet))`

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +    def encrypt(self):
Корректнее воспользоватся модулем abc (abstract base class). Но в этом случае можно и так оставить.

2020-12-24 01:44 UTC, ivanaxe commented on encryptor.py
> +        for letter in buffer:
`for letter in input.read():`
Этого достаточно.

2020-12-24 17:48 UTC, Khaymon commented on encryptor.py
> +        if not key.isdecimal():
Исправил

2020-12-24 17:48 UTC, Khaymon commented on encryptor.py
> +        for letter in buffer:
Сделано

2020-12-24 17:49 UTC, Khaymon commented on encryptor.py
> +            data[letter.lower()] += 1
Подправил

2020-12-24 17:49 UTC, Khaymon commented on encryptor.py
> +        for letter in buffer:
Сделал

2020-12-25 16:58 UTC, ivanaxe approved these changes
Итог : 9

2020-12-25 16:58 UTC, ivanaxe commented on encryptor.py
> +        for letter in buffer:
Ну правда, тут надо было всю лишнюю сложность выкинуть, особенно seek()
на этом seek() падает первый же тест.

Логику с carry_slash в принципе можно было оставить (желательно объяснив при этом, что она делает), фича не очевидная, но выглядит фичей, а не багом.

Так получился итератор, полностью дублирующий уже имеющийся read()

2021-04-20 10:22 UTC, merged